# Desafio 009 - Faça um programa que um número inteiro qualquer e mostre na tela a sua tabuada.
numero = int(input('\nDigite um número inteiro: '))

print('\nTabuada de Adição')
print('................')
print(' ',numero,'+ 0  = ', numero + 0)
print(' ',numero,'+ 1  = ', numero + 1)
print(' ',numero,'+ 2  = ', numero + 2)
print(' ',numero,'+ 3  = ', numero + 3)
print(' ',numero,'+ 4  = ', numero + 4)
print(' ',numero,'+ 5  = ', numero + 5)
print(' ',numero,'+ 6  = ', numero + 6)
print(' ',numero,'+ 7  = ', numero + 7)
print(' ',numero,'+ 8  = ', numero + 8)
print(' ',numero,'+ 9  = ', numero + 9)
print(' ',numero,'+ 10 = ', numero + 10)
print('................\n')